spring:
  datasource:
    url: jdbc:mysql://tripper-db.clj2l5jnnuzc.ap-northeast-2.rds.amazonaws.com:3306/tripperdb
    username: tripper
    password: tripperpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        use-new-id-generator-mappings: false
#    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: testacc0unt.jy@gmail.com
    password: testtest0123
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
  jwt:
    secret: jwtsecretkey

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
