spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/tripper
    username: sa
    password:
    driver-class-name: org.h2.Driver
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: testacc0unt.jy@gmail.com
    password: testtest0123
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
  jwt:
    secret: jwtsecretkey

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8089