spring:
  mvc:
    converters:
      preferred-json-mapper: gson

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        use-new-id-generator-mappings: false
  mail:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
  jwt:
    secret: jwtsecretkey

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace